export const animes = {
    finished: {
        name: "Finished",
        items: [
            { id: 1, content: "Death Note" },
            { id: 2, content: "Ouran High School Host Club" },
            { id: 3, content: "Mob Psycho 100" },
            { id: 4, content: "Kaguya-sama: Love Is War" },
            { id: 5, content: "The Disastrous Life of Saiki K" },
            { id: 6, content: "Yuri!!! on Ice" },
            { id: 7, content: "Buddy Daddies" },
            { id: 8, content: "Wotakoi: Love Is Hard for Otaku" },
            { id: 9, content: "Tomo-chan Is a Girl!" },
            { id: 10, content: "Devilman Crybaby" },
            { id: 11, content: "Life Lessons with Uramichi Oniisan" },
            { id: 12, content: "Sasaki and Miyano" },
            { id: 13, content: "SK8 the Infinity" },
            { id: 14, content: "Ooku: The Inner Chambers" },
            { id: 15, content: "Kamisama Kiss" },
            { id: 16, content: "Yona of the Dawn" },
            { id: 17, content: "Princess Jellyfish" },
            { id: 18, content: "April Showers Bring May Flowers" },
        ],
    },
    inTheMiddleOf: {
        name: "In the Middle Of",
        items: [
            { id: 19, content: "Fruits Basket" },
            { id: 20, content: "TRIGUN" },
            { id: 21, content: "From Me to You: Kimi ni Todoke" },
            { id: 22, content: "Cardcaptor Sakura" },
            { id: 23, content: "Love Through a Prism" },
        ],
    },
    KeepUpWith: {
        name: "Keep Up With",
        items: [
            { id: 24, content: "Chainsaw Man" },
            { id: 25, content: "The Case Study of Vanitas" },
            { id: 26, content: "Haikyuu" },
            { id: 27, content: "Skip and Loafer" },
            { id: 28, content: "Apothecary Diaries" },
            { id: 29, content: "The Summer Hikaru Died" },
            { id: 30, content: "Tamon's B-Side" },
            { id: 31, content: "Journal with Witch" },
            { id: 32, content: "Hana-Kimi" },
        ],
    },
    left: {
        name: "Left",
        items: [
            { id: 33, content: "Spy X Family" },
            { id: 34, content: "Black Butler" },
            { id: 35, content: "Cowboy Bebop" },
            { id: 36, content: "Call of the Night" },
            { id: 37, content: "Jujutsu Kaisen" },
            { id: 38, content: "Bungo Stray Dogs" },
            { id: 39, content: "Banana Fish" },
            { id: 40, content: "Hell's Paradise" },
            { id: 41, content: "Bungo Stray Dogs Wan!" },
            { id: 42, content: "Oshi No Ko" },
            { id: 43, content: "Horimiya" },
            { id: 44, content: "Horimiya: The Missing Pieces" },
            { id: 45, content: "Agents of the Four Seasons: Dance of Spring" },
        ],
    },
    interestedIn: {
        name: "Interested In",
        items: [
            { id: 46, content: "Hunter X Hunter" },
            { id: 47, content: "Moriarty the Patriot" },
            { id: 48, content: "Assassination Classroom" },
            { id: 49, content: "Violet Evergarden" },
            { id: 50, content: "Fullmetal Alchemist: Brotherhood" },
            { id: 51, content: "Another" },
            { id: 52, content: "Orange" },
            { id: 53, content: "Land of the Lustrous" },
            { id: 54, content: "Lycoris Recoil" },
            { id: 55, content: "Ya Boy Kongming!" },
            { id: 56, content: "The Ice Guy and His Cool Female Colleague" },
            { id: 57, content: "Natsuyuki Rendezvous" },
            { id: 58, content: "Raven of the Inner Palace" },
            { id: 59, content: "Special A" },
            { id: 60, content: "Delicious in Dungeon" },
            { id: 61, content: "Code Geass: Lelouch of the Rebellion" },
            { id: 62, content: "X / 1999" },
            { id: 63, content: "Lovely ★ Complex" },
            { id: 64, content: "Monthly Girls' Nozaki-kun" },
            { id: 65, content: "Chihayafuru" },
            { id: 66, content: "Jaadugar: A Witch in Mongolia" },
            { id: 67, content: "Champignon Witch" },
            { id: 68, content: "Natsume's Book of Friends" },
            { id: 69, content: "This Monster Wants to Eat Me" },
            { id: 70, content: "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!" },
        ],
    },
}